### PR TITLE
Allow default values for joints

### PR DESCRIPTION
**Pull request by jmachowinski**
With this commit, it is possible, to set default
values for Joints, that have not reported values yet.
As soon, as a joint reports a value, the default 
is overwritten by it.
This is especially useful, if you have a robot, that 
is missing Joints due to repairs of a arm and you
want to fire up your motion control without big changes.

### CODE REVIEW

**Comment by doudou** [comment]
This should be left out of this component. It makes its logic that much complicated, for something that could very well be done by adding an external constant producer to replace the broken joint.

**Comment by jmachowinski** [comment]
If you need an external component, you'll also need to modify your task network, and the whole dispatcher config. This would make is way less usable.
E.g. :
Joint driver for leg1 : Joint1->Joint4
Joint4 is broken, so I'll set a default value.

If I'll want to use an external component, I would need to either push the joint driver data trough this one, and augment the joint values, need to modify the dispatches, be removing joint4 from teh driver input, and adding a new one for that.

**Comment by doudou** [comment]
> If you need an external component, you'll also need to modify your task network, and the whole dispatcher config. 

Yes. And the price of not doing so is having magically (not) working hard-to-debug networks because of deep magic and "oh the joint stopped sending, but the dispatcher continued sending a default value because of the last time. We crashed into the wall because of that and were that close to kill someone" situations.

In any case, I'm not the maintainer of this package, I don't use it, and this is a disagreement in system integration philosophy. So whoever is in charge of this, feel free to merge. I know I'll have to soft fork a lot of components soon to remove these magic behaviours and pass certification anyways.

**Comment by jmachowinski** [comment]
`<maintainer>Sylvain Joyeus/sylvain.joyeux@m4x.org</maintainer>`  ;-P
The default value is optional. It is only used, if you specify it explicitly for a joint in the config.

**Comment by jmachowinski** [comment]
Nothing else on the behaviour of the joint dispatcher changes

**Comment by doudou** [comment]
> Nothing else on the behaviour of the joint dispatcher changes

If there are no bugs, you are right. That's the thing with ensuring that a component works as intended: even optional behavior you have to test. You have to make sure that noone enables it in your project. Ever. Track all the ways one might be changing it, both in the code and in the configuration files.

Certification requires you to ensure all of this. If there's code, it needs to be tested, documented and have a way to ensure that "bad code" is not enabled. The best way to make sure that it does not bites you is to not have the code in the first place. Reduce the amount of "optional behaviours" from a component makes only sure that you can understand what this component does (and by induction, your whole system).

The integration philosophy that allows you to change your network easily allows this. If you assume your networks are static, then you will just be adding more and more "optional behaviours" or "routing components" in your system, making understanding it that much more difficult.

As I said, I don't use this component, so feel free to ask for its maintainership if you're so inclined.

**Comment by doudou** [comment]
Acknowledged. Go ahead.

**Pull request merged**
